# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    
    filter_sets:
        cache: ~ 
        contacts:
            filters:
                fixed:
                    width: 356
                    height: 515
        users:
            filters:
                fixed:
                    width: 356
                    height: 362